//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Model.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_Order
    {
        public event_Order()
        {
            this.OrderTickets = new HashSet<event_TicketOrder>();
        }
    
        public int Id { get; set; }
        public System.Guid Guid { get; set; }
        public int EventId { get; set; }
        public string UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> OrderTime { get; set; }
        public string PhoneNumber { get; set; }
        public string Billing_Address { get; set; }
        public string Billing_Address2 { get; set; }
        public string Billing_City { get; set; }
        public string Shipping_Address { get; set; }
        public string Shipping_Address2 { get; set; }
        public string Shipping_City { get; set; }
        public string Billing_Country { get; set; }
        public string Shipping_Country { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual event_Event Event { get; set; }
        public virtual ICollection<event_TicketOrder> OrderTickets { get; set; }
    }
}
