//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Model.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_TicketOrder
    {
        public event_TicketOrder()
        {
            this.event_Ticket = new HashSet<event_Ticket>();
        }
    
        public int Id { get; set; }
        public System.Guid Guid { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
    
        public virtual ICollection<event_Ticket> event_Ticket { get; set; }
    }
}
