//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Model.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_Ticket
    {
        public event_Ticket()
        {
            this.event_TicketOrder = new HashSet<event_TicketOrder>();
        }
    
        public int Id { get; set; }
        public int EventId { get; set; }
        public System.Guid Guid { get; set; }
        public string Name { get; set; }
        public int Quantity { get; set; }
        public int AvailableTicketQuantity { get; set; }
        public string Description { get; set; }
        public bool IsShowDescription { get; set; }
        public int SaleChanel { get; set; }
        public Nullable<int> SaleEndOption { get; set; }
        public bool IsHide { get; set; }
        public int MinimunTicketOrder { get; set; }
        public int MaximunTicketOrder { get; set; }
        public string TicketCode { get; set; }
        public int Status { get; set; }
        public int SortOrder { get; set; }
        public decimal Price { get; set; }
        public System.DateTime StartSaleDateTime { get; set; }
        public Nullable<System.DateTime> EndSaleDateTime { get; set; }
        public int Type { get; set; }
    
        public virtual event_Event Event { get; set; }
        public virtual ICollection<event_TicketOrder> event_TicketOrder { get; set; }
    }
}
