//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Model.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class event_TicketOrder
    {
        public int TicketId { get; set; }
        public int OrderId { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual event_Order Order { get; set; }
        public virtual event_Ticket Ticket { get; set; }
    }
}
