//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.Model.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class system_Profiles
    {
        public System.Guid UserId { get; set; }
        public string UserName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<int> Status { get; set; }
        public string Prefix { get; set; }
        public string HomePhone { get; set; }
        public string MobilePhone { get; set; }
        public string JobTitle { get; set; }
        public string Company { get; set; }
        public string Website { get; set; }
        public string Blog { get; set; }
        public string Home_Address { get; set; }
        public string Home_Address2 { get; set; }
        public string Home_City { get; set; }
        public string Billing_Address { get; set; }
        public string Billing_Address2 { get; set; }
        public string Billing_City { get; set; }
        public string Shipping_Address { get; set; }
        public string Shipping_Address2 { get; set; }
        public string Shipping_City { get; set; }
        public string Work_Address { get; set; }
        public string Work_Address2 { get; set; }
        public string Work_City { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> Age { get; set; }
    }
}
